[mitm]
hostname = i.ostrichvpn.net, *.ostrichvpn.net, fastconn.github.io

[rewrite_local]
^https?://i\.ostrichvpn\.net/(a/|config|pro|unlock|subscribe|user|load) url script-response-body https://raw.githubusercontent.com/389qhp/ostrich-unlock/main/ostrich_pro.js